import { AnalysisResult, Stats, ComplianceFinding } from './api';

// Mock findings data
const mockFindings: ComplianceFinding[] = [
  {
    id: '1',
    type: 'security',
    severity: 'critical',
    message: 'Hardcoded API key detected in source code',
    file: 'src/config/api.js',
    line: 42,
    column: 15,
    code: "const API_KEY = 'TOKEN';",
    fixSuggestion: 'Move API key to environment variables or use a secure secrets manager',
    ruleId: 'secret-api-key',
    ruleName: 'Hardcoded API Key',
  },
  {
    id: '2',
    type: 'security',
    severity: 'critical',
    message: 'AWS Access Key ID found in configuration',
    file: 'config/aws.json',
    line: 8,
    column: 12,
    code: '"accessKeyId": "TOKEN"',
    fixSuggestion: 'Use AWS IAM roles or AWS Secrets Manager instead of hardcoded credentials',
    ruleId: 'secret-aws-key',
    ruleName: 'AWS Access Key',
  },
  {
    id: '3',
    type: 'security',
    severity: 'high',
    message: 'Potential SQL injection vulnerability detected',
    file: 'src/db/queries.js',
    line: 67,
    column: 25,
    code: "const query = `SELECT * FROM users WHERE id = ${userId}`;",
    fixSuggestion: 'Use parameterized queries or prepared statements to prevent SQL injection',
    ruleId: 'security-sql-injection',
    ruleName: 'SQL Injection Risk',
  },
  {
    id: '4',
    type: 'security',
    severity: 'high',
    message: 'Use of eval() detected - can execute arbitrary code',
    file: 'src/utils/parser.js',
    line: 23,
    column: 8,
    code: "const result = eval(userInput);",
    fixSuggestion: 'Avoid eval() and use safer alternatives like JSON.parse() or a proper parser',
    ruleId: 'security-eval',
    ruleName: 'Dangerous eval() Usage',
  },
  {
    id: '5',
    type: 'license',
    severity: 'high',
    message: 'GPL-licensed library detected in proprietary codebase',
    file: 'package.json',
    line: 15,
    column: 2,
    code: '"some-library": "^2.0.0"',
    fixSuggestion: 'Replace with MIT/Apache licensed alternative or open source your code',
    ruleId: 'license-gpl-violation',
    ruleName: 'GPL License Violation',
  },
  {
    id: '6',
    type: 'security',
    severity: 'medium',
    message: 'Weak cryptographic algorithm detected (MD5)',
    file: 'src/auth/hash.js',
    line: 12,
    column: 18,
    code: "const hash = crypto.createHash('md5').update(password).digest('hex');",
    fixSuggestion: 'Use strong algorithms like SHA-256 or bcrypt for password hashing',
    ruleId: 'security-weak-crypto',
    ruleName: 'Weak Cryptography',
  },
  {
    id: '7',
    type: 'quality',
    severity: 'low',
    message: 'Missing license header in source file',
    file: 'src/api/routes.js',
    line: 1,
    column: 1,
    code: "const express = require('express');",
    fixSuggestion: 'Add appropriate license header to file',
    ruleId: 'license-missing-header',
    ruleName: 'Missing License Header',
  },
  {
    id: '8',
    type: 'quality',
    severity: 'info',
    message: 'Console.log statement found in production code',
    file: 'src/middleware/auth.js',
    line: 45,
    column: 5,
    code: "console.log('User authenticated:', user.id);",
    fixSuggestion: 'Use proper logging framework instead of console.log',
    ruleId: 'quality-console-log',
    ruleName: 'Console Log Statement',
  },
  {
    id: '9',
    type: 'quality',
    severity: 'info',
    message: 'TODO comment found in code',
    file: 'src/services/payment.js',
    line: 89,
    column: 3,
    code: "// TODO: Implement retry logic for failed payments",
    fixSuggestion: 'Create issue or resolve TODO',
    ruleId: 'quality-todo-comment',
    ruleName: 'TODO Comment',
  },
  {
    id: '10',
    type: 'security',
    severity: 'high',
    message: 'Hardcoded password detected',
    file: 'src/config/database.js',
    line: 5,
    column: 18,
    code: "password: 'admin123456'",
    fixSuggestion: 'Use environment variables or secure vaults for passwords',
    ruleId: 'secret-password',
    ruleName: 'Hardcoded Password',
  },
];

// Generate mock analysis results
export const mockAnalyses: AnalysisResult[] = [
  {
    id: 'analysis-1',
    prNumber: 142,
    repoFullName: 'acme-corp/backend-api',
    status: 'completed',
    findings: mockFindings.slice(0, 6),
    analyzedAt: new Date(Date.now() - 2 * 60 * 60 * 1000), // 2 hours ago
    duration: 4500,
    stats: {
      totalFiles: 12,
      totalFindings: 6,
      critical: 2,
      high: 3,
      medium: 1,
      low: 0,
      info: 0,
    },
  },
  {
    id: 'analysis-2',
    prNumber: 89,
    repoFullName: 'acme-corp/frontend-app',
    status: 'completed',
    findings: mockFindings.slice(2, 8),
    analyzedAt: new Date(Date.now() - 5 * 60 * 60 * 1000), // 5 hours ago
    duration: 3200,
    stats: {
      totalFiles: 8,
      totalFindings: 6,
      critical: 0,
      high: 2,
      medium: 2,
      low: 1,
      info: 1,
    },
  },
  {
    id: 'analysis-3',
    prNumber: 203,
    repoFullName: 'acme-corp/microservice-auth',
    status: 'completed',
    findings: mockFindings.slice(0, 4),
    analyzedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000), // 1 day ago
    duration: 2800,
    stats: {
      totalFiles: 5,
      totalFindings: 4,
      critical: 2,
      high: 2,
      medium: 0,
      low: 0,
      info: 0,
    },
  },
  {
    id: 'analysis-4',
    prNumber: 156,
    repoFullName: 'acme-corp/data-processor',
    status: 'completed',
    findings: mockFindings.slice(4, 10),
    analyzedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000), // 2 days ago
    duration: 5100,
    stats: {
      totalFiles: 15,
      totalFindings: 6,
      critical: 0,
      high: 1,
      medium: 1,
      low: 1,
      info: 3,
    },
  },
  {
    id: 'analysis-5',
    prNumber: 78,
    repoFullName: 'acme-corp/mobile-app',
    status: 'completed',
    findings: mockFindings.slice(1, 7),
    analyzedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000), // 3 days ago
    duration: 3800,
    stats: {
      totalFiles: 10,
      totalFindings: 6,
      critical: 1,
      high: 3,
      medium: 1,
      low: 0,
      info: 1,
    },
  },
  {
    id: 'analysis-6',
    prNumber: 234,
    repoFullName: 'acme-corp/infrastructure',
    status: 'completed',
    findings: mockFindings.slice(3, 6),
    analyzedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000), // 4 days ago
    duration: 2100,
    stats: {
      totalFiles: 6,
      totalFindings: 3,
      critical: 0,
      high: 2,
      medium: 1,
      low: 0,
      info: 0,
    },
  },
];

// Mock stats
export const mockStats: Stats = {
  totalAnalyses: 6,
  totalFindings: 31,
  criticalIssues: 5,
  highIssues: 11,
  mediumIssues: 5,
  lowIssues: 2,
  infoIssues: 8,
  avgDuration: 3583,
};

// Get mock analysis by ID
export function getMockAnalysis(id: string): AnalysisResult | undefined {
  return mockAnalyses.find(a => a.id === id);
}

